#!/usr/bin/env python3
from pexpect import pxssh
import time
from getpass import getpass
import sys
from cmd import Cmd
from cisco import start
from hp1820cli import sshhp

if len(sys.argv) != 2:
	print("[user@]host")
	print("(If not specified, the username of hp is admin.)")
	sys.exit(0)
check = input("Cisco[c] or Hp[h]?")
if check == "c":
	start.sshcisco(sys.argv[1])
else:
	sshhp.hpswitch(sys.argv[1])
